### ISSUE TITLE
JSON POST request body is mapped to query params with expressify

### ISSUE THREAD

**Issue by icaraps** [adobe/openwhisk-action-utils#214]
Based on https://github.com/adobe/openwhisk-action-utils/blob/main/src/expressify.js#L80, and given a JSON post request like 
```
fetch(RT_ACTION, {
  method: 'post',
  body: JSON.stringify({name: 'Stephan'}),
  headers: {
    'content-type': 'application/json'
  }
})
```

In openwhisk, the body will be available in `params` eg `params.name === 'Stephan'` and mapped as query params instead of body by expressify.

**Comment by tripodsan** [comment]
for POST body to work, use `raw` openwhisk actions.

**Comment by icaraps** [comment]
Yes it's working, thank you. Based on https://github.com/apache/openwhisk/blob/master/docs/webactions.md#raw-http-handling, if using runtime, you can set `web: 'raw'` in the manifest for POST body to work, but then you have to parse it yourself.

**Comment by icaraps** [comment]
Also see https://medium.com/openwhisk/whats-new-web-actions-e0ffeef1bea3 which explains it well.

**Comment by tripodsan** [comment]
I close this as won't fix
