### ISSUE TITLE
Provide action chaining mechanism

### ISSUE THREAD

**Issue by tripodsan** [adobe/openwhisk-action-utils#25]
It is useful to _wrap_ the action's main function with several helper plugins. however, overuse will result in unreadable code:

```js
async run(params) {
    ...my action code...
}

async main(params) {
   return logger.wrap(status.wrap(epsagon.wrap(run), params);
}
```

It might be more useful to create tooling that allows chaining:

```js
async main(params) {
    ...my action code...
}

module.exports.main = chain()
   .use(logger)
   .use(status)
   .use(epsagon)
   .run(main);
```

/cc @trieloff

**Comment by trieloff** [comment]
```javascript
module.exports.main = chain(main)
   .use(logger)
   .use(status)
   .use(epsagon);
```

would be my suggestion.
`chain` would return the argument, plus a `use` function. `use` would wrap `this` and run `chain` on the result.

**Comment by tripodsan** [comment]
hmm...I don't like that the order is not intuitive....

**Comment by tripodsan** [comment]
as mentioned in the PR, maybe this syntax would more intuitive:

```js
module.exports.main = wrap(main)
  .with(epsagon)
  .with(status)
  .with(logging)
```

although the _execution_ order is reverse, it forms a better english sentence.
