### ISSUE TITLE
move logger to own repository

### ISSUE THREAD

**Issue by tripodsan** [adobe/openwhisk-action-utils#42]
Decouple logger to own repository to keep depndency baggage low

**Comment by tripodsan** [comment]
@trieloff  WDYT? I thought of `openwhisk-action-logger`

(alternatively, we could also reuse https://github.com/adobe/openwhisk-loggly-wrapper and rename it)

**Comment by trieloff** [comment]
Sounds good. Creating a repo from scratch now takes 15 minutes. If that's faster than re-using the old wrapper repo, let's do it.

**Comment by tripodsan** [comment]
ok. let's create a new one to keep it transparent

**Comment by tripodsan** [comment]
@trieloff can you create `openwhisk-action-logger` ?
